### ISSUE TITLE
osmium cat support for jsonseq

### ISSUE THREAD

**Issue by rclark** [osmcode/osmium-tool#114]
I would like to use `osmium cat` to convert a planet.pbf file into a sequence of line-delimited JSON strings that I can easily read into a Spark application. Currently, I need to use the `opl` format as an intermediate step. Doing the transformation from opl --> json is just string manipulation, but it is costly for 3+ billion lines using the platforms that I'm constrained to(javascript or pyspark are basically my options).

@joto I'm curious if there are any hidden problems in representing raw node/way/relation as JSON strings that have prevented you from supporting it as an output format? Would it be challenging to add such a feature to `osmium cat`?

**Comment by joto** [comment]
Osmium-tool simply simply supports all formats supported by libosmium. There is no JSON format support for OSM files in libosmium because nobody defined a JSON format for OSM files. There was an effort several years back to add a JSON format for the OSM API, but that never came to be. If somebody defines a JSON format, it could be added to libosmium and would then be supported by `osmium cat`. It would add a dependency to libosmium on some kind of JSON library, but that can't be helped. (osmium-tool already uses RapidJSON, libosmium doesn't.) Because there are many different ways the OSM data could be expressed in JSON there should be some community discussion and consulting with those people who want to use JSON for the API to make sure we don't get incompatible formats.

That being said, it shouldn't be a huge problem to write a standalone C++ application that converts OSM data to any JSON format you would like to have for your specific use case. This wouldn't be in the generic osmium-tool, because it is not a standardized format and not generally useful, but that doesn't mean it can't be its extra tool.

**Comment by rclark** [comment]
Thanks for the context @joto -- sounds like any further actions would happen elsewhere, so closing here.

ps the target JSON format in my use-case is effectively identical to the XML schema, and also matches [the format of the public dataset hosted by AWS](https://docs.opendata.aws/osm-pds/readme.html).

```
CREATE EXTERNAL TABLE planet (
  id BIGINT,
  type STRING,
  tags MAP,
  lat DECIMAL(9,7),
  lon DECIMAL(10,7),
  nds ARRAY<STRUCT>,
  members ARRAY<STRUCT>,
  changeset BIGINT,
  timestamp TIMESTAMP,
  uid BIGINT,
  user STRING,
  version BIGINT,
  visible BOOLEAN
)
```
