### ISSUE TITLE
untagged nodes referenced by relations are dropped by osmium add-locations-to-ways

### ISSUE THREAD

**Issue by jonathanl-telenav** [osmcode/osmium-tool#117]
preprocessing PBF files with osmium the "add-locations-to-ways" feature causes untagged "via" nodes in turn restriction relations to be missing from the output (the tagged ones are fine, of course). since node relation members don't have lat/lon information, it doesn't seem possible to get the lat lon of these nodes in a processed file.

**Comment by joto** [comment]
Use the `--keep-untagged-nodes` option.

**Comment by jonathanl-telenav** [comment]
yes, we tried that. unfortunately, that option hasn't worked for us. it means we have to process billions of nodes we don't care about when processing a planet file, which causes memory issues even on a cluster. one of the main reasons that we're using add-locations-to-ways is so we can avoid keeping the untagged nodes.

**Comment by joto** [comment]
Well, I am not sure what to answer here, because I don't know what your question actually is. Not sure why you need to process all the nodes when all that you are interested in are turn restriction relations. You can use `osmium tags-filter` to filter out only the turn restrictions, something like  `osmium tags-filter planet.osm.org r/type=restriction -o turn-restrictions.osm.pbf` should do the job. The result is then small enough that any other type of processing you do should be easy and fast enough. There are other ways to approach this, but I don't know enough about what your environment and requirements are to say something about this.

**Comment by jonathanl-telenav** [comment]
hi jochen, i think the issue i was looking at is not actually an osmium issue after all. there is an issue in osmium-processed files relating to via nodes, but it appears the issue isn't due to the actual osmium processing, it's something else in my code somewhere. so, i think we can close this ticket. thanks for your time.
