### ISSUE TITLE
Why are negative ids sorted by absolute value and not -2, -1 and so on?

### ISSUE THREAD

**Issue by amenk** [osmcode/osmium-tool#121]
Is that some kind of standard?

I am asking because https://github.com/mapsme/omim does not support it

**Comment by joto** [comment]
There is no standard for sorting negative IDs, there isn't even a clear understanding how negative IDs are to be used. The most prominent program using negative IDs is JOSM and Osmium sorts them the way JOSM does, because of this.

I would expect that most programs don't understand negative IDs at all, or, if they do, more by accident than by design, because negative IDs are rare and don't happen in normal OSM data. Maybe you should raise this issue with mapsme and see what they say?

**Comment by amenk** [comment]
Thanks. Asked there... What do you think about adding an additional sort option to osmium-tool?
