### ISSUE TITLE
tags-filter - logical AND?

### ISSUE THREAD

**Issue by Murmand** [osmcode/osmium-tool#126]
First of all, thank you for this great tool. I went through all issues here and read the whole manual page, but I am still not able to achive this use case:

I would like to filter all items matching tags **water** AND **name** together. For example:

 - `water,name` will find all items with **water** OR **name** tag.
 - `water name` does the same

But I need logical AND. Something like `water+name` (which is not working now)

So I tried to make it like this:

```
osmium tags-filter -o 01.osm.pbf origin.osm.pbf name
osmium tags-filter -o 02.osm.pbf 01.osm.pbf water
```

But there is one issue I do not understand. It depends on the order. If I filter it by **name** firstly and then by **water**, the result is different than if I filter it viceversa. (You can try it with this dataset: http://download.geofabrik.de/europe/czech-republic-latest.osm.pbf)

How can I achieved that reliably? I have to be sure there is no missing items. Thank you!

**Comment by joto** [comment]
There is currently no way to do this with Osmium alone in a general fashion. Osmium doesn't have a general-purpose expression engine built in to keep it simpler and performant. In general the suggested solution is to use Osmium to first do a rough filter that reduces the data to a manageable level and then use other tools, such as PyOsmium or simply Unix tools such as grep or a Perl script or whatever to do the rest. If you reduce the huge amount of OSM data using Osmium to only the data that contains a water tag, the result should be managable with any old programming tool you want to use.

The reason you are seeing differences depending on the order of the two filter command is probably that `tags-filter` will include all depending objects (ie nodes referenced in ways etc).

There are several solutions you can try depending on what data you actually need in what form etc. If you only need the ways with both those tags using `osmium tags-filter -f pbf origin.osm.pbf w/water | osmium tags-filter -o out.osm.pbf - w/name` should get you those ways. You can then use `osmium getid -r -I` to get referenced nodes back. If you also need relations it becomes a bit more difficult, but that's just due to the complicated osm data model (what if you have a relation with a water tag but no name, but a member way with a name and no water tag etc). To give you more specific advice I'd have to know exactly what it is you want to get out of this.

**Comment by Murmand** [comment]
Thank you for your response. I would like to get out of this all polygons of items with `water` and `name` tags. But I think it should be ok to filter all items with `water` tag, export the result and than use another tool to postprocess.
