### ISSUE TITLE
PG export stores simple Polygons as Multipolygons

### ISSUE THREAD

**Issue by Komzpa** [osmcode/osmium-tool#153]
WKB representation for Polygons is always Multipolygon, even when there is just single outer ring. This adds extra bytes on record header and forces PostGIS to do an extra dive into collection for every such polygon, sometimes disregarding more efficient code paths. 

note no ST_Polygon here:
```
gis=# select  osm_type, ST_GeometryType(geom::geometry), count(*) from osm group by 1,2;
 osm_type | st_geometrytype |  count  
----------+-----------------+---------
 way      | ST_LineString   | 3080164
 relation | ST_MultiPolygon |   37035
 way      | ST_MultiPolygon | 2166027
 node     | ST_Point        |  560108
(4 rows)
```

**Comment by joto** [comment]
That is on purpose because it is much easier for anybody using the data to just have one polygon geometry data type instead of two. If you don't like this, create a new table and copy the data over using `ST_Dump()` in the process. The format created by Osmium is not necessarily the best format for any kind of use. But that doesn't matter because you have the power of PostgreSQL/Postgis to convert it into something that is more suitable for your use case.
