### ISSUE TITLE
Add raw osm data to PG export

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#154]
Can raw OSM data (particularly non-spatial relations, way members etc.) be added as an option of PG export? Something like osmosis output or osm2pgsql slim mode output?

**Comment by joto** [comment]
Wouldn't be much of an export if it is just raw OSM data.The whole point of the `export` command is that it gives you "cooked" data for use in other contexts.

I am not sure what you mean with "osmosis output" or "osm2pgsql slim mode output". Osmosis outputs a lot of different formats and osm2pgsql is a database importer. Maybe you are talking about some kind of database importer here, but can you be more specific? What do you need that's not supported by existing tools such as osmosis, osm2pgsql, or imposm? Maybe this is something that would be better added to those tools?

**Comment by nextstopsun** [comment]
Conversion of raw OSM data to a `COPY` compatible format is quite cool by itself, so I'd stand for it's usefulness.

My point is that some important OSM data, like transport route relations etc. doesn't land to a `PG` format, so it'd be nice to have it there.

Importers do the job fine, but `COPY` performance is really outstanding, so in some cases loading data with it is preferable to importers.

**Comment by joto** [comment]
The importers should really also use `COPY` and probably are. If their performance isn't as good as Osmium's that's because they are doing a lot more work, work that Osmium would also have to do, if it didn't have only the simplistic `export` command but could also do more fancy things. For instance, at the moment the `export` command is so simple because it creates a single table, so one `COPY` is enough. But for many use case, to actually use this table, you have to split it up inside the database. A "real" importer will do this for you. If we add more stuff, like route relations, we'd have to write many more tables which makes things slower. etc.

Adding all this is out-of-scope for Osmium. Of course if somebody wants to use libosmium to write a database importer, they can do that, but Osmium isn't trying to replace osm2pgsql.

**Comment by nextstopsun** [comment]
Of course osmium shouldn't be an importer. I'd just be great to have all data in PG format. It's ok if it falls to one table (as it does now), it's either ok if relations don't get parsed by importer etc. DB can handle all data manipulation quite well.

The case of the issue is just to have all objects from pbf file (including relations) imported to the DB. No extra logic needed :)

**Comment by joto** [comment]
How do you propose to add complex datastructures like the relation to a database without using several tables?

**Comment by nextstopsun** [comment]
Easy: you can use existing table, leave geometry empty for relation objects and just add a column`members` of `JSONB` type with a json array of `[{<osm_id>:<member role>}]`.  
Could be even easier with plain postgres array of string values, like so ```{w46276184,from,w28089310,to,n308489027,via}```
You can even reuse this array for ways to include a list of nodes for every way.

**Comment by joto** [comment]
If you can work with raw data like this maybe you can use the OPL format, change every space into a tab and COPY that into the database and do all your postprocessing there.

Anyway this is not going anywhere. There are a million different ways of importing OSM data into a database and everybody needs their own format. It would be nice and useful to have a tool like this, but Osmium is not it.

**Comment by joto** [comment]
I have started some experiments here: https://github.com/osmcode/osm-postgresql-experiments . No promises that this will go anywhere, though.

**Comment by nextstopsun** [comment]
@joto Looks great (especially array of rel_member type). 
Would there be an option to not build way geometry? This could be quite time consuming process.

Aside from that thanks for a tip on importing OPL format. The hardest part is changing spaces to tabs, because you have to deal with escaped spaces in tags. Is it possible to have an option for setting a delimiter symbol when writing to OPL?

**Comment by joto** [comment]
Lets not turn this issue into a discussion of multiple things. It makes keeping track hard. In the future please open single issues for each issue on the repositories where they belong. But to make this short:

* The way geometry is built as an extra step in SQL, just don't run that and you are fine.
* Turns out you don't need to turn the spaces into tabs, because you can add a `DELIMITER` to the `COPY` command. And spaces are already escaped in the OPL format, so this works fine. But the escaping (of spaces and other characters) in OPL can be annoying for this, you probably want to revert that in SQL. I leave the details as an exercise for the reader.
