### ISSUE TITLE
How to get timestamp of osc file with osmium fileinfo?

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#157]
I'd like to get timestamp of an `osc` file with `osmium fileinfo` utility.
Command `osmconvert diff.osc --out-timestamp` returns a timestamp of a changeset file.
But commands
`osmium fileinfo -g header.option.timestamp diff.osc`
or
`osmium fileinfo -g metadata.all_objects.timestamp diff.osc` 
on the same file return empty output.

**Comment by joto** [comment]
The setting is called `header.option.osmosis_replication_timestamp`. But I don't believe osc files have timestamps, the hourly diff files from planet.osm.org I just checked don't have any. Any `osmconvert` reports `(invalid timestamp)` for it.

`metadata.all_objects.timestamp` is something different: It tells you whether all objects in the file have a timestamp. This is to detect whether you have complete data or some attributes are missing (possibly due to privacy considerations).

**Comment by nextstopsun** [comment]
I'm querying a diff file that was downloaded and merged from planet changesets by `osmupdate` tool and get a timestamp in the output.

Slightly off topic: My goal is to set a timestamp for a `osmium apply-changes` result, so next time `osmupdate` knows from which timestamp to start downloading diffs.
What is a common way to do that?

**Comment by joto** [comment]
The best way to do this is to use `pyosmium-up-to-date` (part of PyOsmium) which magically keeps a planet file up to date.

**Comment by nextstopsun** [comment]
AFAIK pyosmium-up-to-date doesn’t save accumulated diff osc file, which I use to update postgres DB.

**Comment by joto** [comment]
There is a companion program called `pyosmium-get-changes` for that use case.
