### ISSUE TITLE
osmium-export way_nodes attribute does not work on areas built from closed ways

### ISSUE THREAD

**Issue by Timost** [osmcode/osmium-tool#164]
Hi,
Following our discussion in #163, I've been looking at including the ways' nodes ids in my data.
I'm using `osmium-export` to convert a pbf to geojson, and I want to keep using it as it's quite fast.

While reading the [osmium-export](https://docs.osmcode.org/osmium/latest/osmium-export.html) I found the `attributes.way_nodes` option in the export config file that seems to be what I want.

The issue is I can't seem to get any `propeties.@way_nodes` in the geojson output for the ways that end up being areas (geojson MultiPolygons). I've tested this with the `1.10.0` and the `1.9.1` version of `osmium-tool` without success. 

In the manual I've seen this line, in the "Attributes" section:

> way_nodes (ways only, array with node IDs)

But since areas are basically closed ways (or relations with the "type=multipolygon or type=boundary"), I was expecting `way_nodes` to also work for areas. Is this the expected behaviour ?

Step to reproduce:
```
mkdir test_way_nodes
wget http://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -O test_way_nodes/berlin-latest.osm.pbf
osmium export test_way_nodes/berlin-latest-filtered.osm.pbf -o test_way_nodes/berlin-latest.json -f geojsonseq -c osmium-export-config.json --overwrite --omit-r -v --geometry-type=polygon
cat test_way_nodes/berlin-latest.json | grep '"@way_nodes" | wc -l
```

**Comment by joto** [comment]
Areas are "special" in Osmium. They aren't real objects, but they are, as you mention, created from either ways or multipolygon relations. They are not ways, so, yes, this is the expected behaviour. The reason behind this, is that areas are meant to "hide" their origin, you are not supposed to care whether they are created from a way or a relation. But the `way_nodes` would only work for areas created from ways. For areas created from relations a simple list of nodes is not enough, because there might be multiple rings in them, so you'd need lists of lists of lists of nodes. The job of `osmium export` is to *export* the data into other formats, if you need the original details of the data, it is the wrong tool.

Anyway, if this would work, you'd still need the member ways for the relations and not only the nodes.

**Comment by Timost** [comment]
Thank you again for your fast answers ! 

I get your point, especially for the multipolygon relations.

I'll try building my own tool and see where it gets me.
