### ISSUE TITLE
osmium extract should copy timestamp

### ISSUE THREAD

**Issue by flohoff** [osmcode/osmium-tool#170]
Hi,

it would be nice if **osmium extract** could keep the timestamp and/or the replication timestamp if the originating file had one.

This would make it possible to track extracts age

Flo

**Comment by Nakaner** [comment]
A workaround is to get these file headers using `VAL=$(osmium fileinfo -g $KEY)` and set it using `osmium extract --output-header=$KEY=$VAL ...`.

**Comment by joto** [comment]
I have added a special syntax to the `--output-header` option to make this somewhat easier. You can set, for instance, the timestamp with `--output-header=osmosis_replication_timestamp!`. The exclamation mark at the end says: take this value from the input header.

I decided against making this fully automatic, because there are cases where you want to generate replication diffs for extracts and in this case the headers would clash.

Currently in master only.

Does this help?
