### ISSUE TITLE
Export custom relations with osmium-export

### ISSUE THREAD

**Issue by maning** [osmcode/osmium-tool#223]
@joto Based on the [docs](https://docs.osmcode.org/osmium/latest/osmium-export.html), osmium-export have limited functionality to export different type of relations to geojson.  

We wanted to use osmium-export for custom relations very similar to [`type=site`](https://wiki.openstreetmap.org/wiki/Relation:site), where each node has custom roles.

Do we have examples of export config that does this?

**Comment by joto** [comment]
Osmium export doesn't support any relations type other then multipolygon/boundary because it isn't clear what the geometry should look like for these kinds of objects. For a `site` relation it might make sense to create a geometry collection of (some of) its members, or it might make sense to create the hull of all these geometries for instance. But the functionality might also depend on the member roles or the tags of the members. The multipolygon/boundary relations are the main relation type in common use where the semantic of the type is actually quite well understood and consistently used, so that's implemented. But for other types this isn't necessarily the case, so this just can't be done currently with osmium alone.

**Comment by maning** [comment]
@joto TYVM for the explanation.
