### ISSUE TITLE
Multi extracts diff merge return osc order dependent result

### ISSUE THREAD

**Issue by frodrigo** [osmcode/osmium-tool#282]
```
osmium --version
osmium version 1.13.1
libosmium version 2.16.0
```

I try to merge 2 osc from OSM-FR for 2 extracts with a common boundary.

In one osc an object is marked as `modify` in the other as `deleted`, with the same version. It was not delete from OSM. It is marked as deleted in one osc because it is out of extract polygon. 

I try to merge the osc
```
osmium merge-changes --simplify -o osmium-merge-alava-guipuzcoa.osc.gz diff-alava-1733847895.osc.xml.bz2 diff-guipuzcoa-1733847895.osc.xml.bz2
osmium merge-changes --simplify -o osmium-merge-guipuzcoa-alava.osc.gz diff-guipuzcoa-1733847895.osc.xml.bz2 diff-alava-1733847895.osc.xml.bz2
```

But the result is order dependent. In one case the object is out as `modify` in the merged osc, in the other case is out as `deleted`.

The sort is done here
- https://github.com/osmcode/osmium-tool/blob/master/src/command_apply_changes.cpp#L350
- https://github.com/osmcode/libosmium/blob/master/include/osmium/osm/object_comparisons.hpp#L161

The deleted flag is not used.

I suppose this case could be supported.

If the object is deleted in all osc, then we expect it to be delete in the output as it is really deleted or out of polygon for all extracts. But if it is not deleted in at least in one osc, it is still present in OSM data as not deleted.

This could be achieve by including the delete flag in the comparator function.

Do you think this could be right ? or I miss something.

I join sample data.
[osmium-merge-order.zip](https://github.com/user-attachments/files/18083561/osmium-merge-order.zip)

**Comment by joto** [comment]
Your analysis sounds correct to me. I am not sure yet how to solve this, whether I can just change the implementation of `osmium::object_order_type_id_reverse_version` to take the delete into account or need a different variant of that comparison. I'll have to look through all the cases where it is used.

**Comment by joto** [comment]
I have changed the implementation of `osmium::object_order_type_id_reverse_version` in libosmium commit cff8ff42. So you need to recompile osmium-tool with libosmium master and then it should work as intended.

**Comment by joto** [comment]
I am reverting the change, see discussion here: https://github.com/osmcode/libosmium/issues/403

There are several problems here:
1. The original logic in `merge-changes` was created for a different use-case than yours. The use case is that you want to merge several change files from different points in time for the same area into a single change. In that case the *last* change (in a temporal sense) should always win. This use-case is broken by the changes proposed here. That's why we have to revert them.
2. The problem that you are trying to solve (merging extracts from the same point in time for different areas) can not be solved in all cases, because the change files don't contain enough information.

Here is a case to illustrate this: You have two extracts **A** and **B** with a common border. Node **X** is in **A**, it is part of a way **W** that has more nodes in **B**. So in the start position **W** is in extract **A** and in extract **B**. Now node **X** moves from area **A** to area **B**. You'll get a "delete change" for **W** in extract **A**, because **W** is now completely outside **A**. But for extract B you get nothing, because **W** was in **B** before the change and it still is after the change. Its geometry has changed, but that's only reflected in node **X**, not way **W**. So you would still delete **W** in the merged diff, because you only see the one "delete change".

So there might be some cases that you proposed change fixes, but not all of them. There simply is not way to reliable merge changes from different extracts without having extra information. I'll add a note in the man page of `osmium merge-changes` to that effect.
