### ISSUE TITLE
osmium sort on negative IDs

### ISSUE THREAD

**Issue by andrewharvey** [osmcode/osmium-tool#30]
I've read the man pages but I'm still stuck as to why:

`1.osm`:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6">
    <node id="-1" lat="-33.7077207" lon="151.1745444"/>
    <node id="-2" lat="-33.7078497" lon="151.1746207"/>
</osm>
```

`osmium sort --output=2.osm 1.osm`

Is keeping the order -1 then -2. So when I then run

`osmium renumber --output=3.osm 2.osm`

There is the error:

```
Node IDs out of order.
This command expects the input file to be ordered: First nodes in order of ID,
then ways in order of ID, then relations in order of ID.
```

`osmium help sort` says that Objects are sorted by ID and it works with OSM data files and change files. The `1.osm` file was created by saving new data from JOSM.

The point of running `osmium renumber` is to keep the IDs small and use positive integers, but it requires input to be sorted first.

`osmium renumber` works when I manually change the order to -2 then -1.

I used to use `osmium renumber` without pre-sorting the data which seemed to work fine but due to changes to renumber in 1.3.1 I now run into this issue.

**Comment by joto** [comment]
The problem is that renumber just can't handle negative IDs. Unfortunately I didn't document it and didn't tell it to write a nice error message in this case, because this case never occurred to me. 

Unfortunately it isn't easy to put that in, so I am not sure when I can fix that.

**Comment by pnorman** [comment]
It's a bit fragile because it relies on how the XML is output, but my workflow is

```
osmium sort --output=2.osm 1.osm
sed -i 's/id="-/id="/g' 2.osm
sed -i 's/ref="-/ref="/g' 2.osm
osmium renumber --output=3.osm 2.osm
```

**Comment by joto** [comment]
If you are doing shenanigans like that, I recommend using the OPL format instead of XML. The format is much easier to handle in scripts like that, because it is more strict than the XML.

**Comment by aaabuabat** [comment]
Hi, 

I know this is a "too late" response :). However, I just want to share my experience, so if someone had the same issue; he or she can find a further solution. 

I faced this problem while I am trying to extract the full history for Pennsylvania state in the USA, from this file "north-america.osh.pbf" (see http://download.geofabrik.de/north-america.html). 

I was doing this when I got this message: 
`osmium extract --bbox LEFT,BOTTOM,RIGHT,TOP [OPTIONS] OSM-FILE -o OUT-PUT-FILE`

In my case was: 
`osmium extract --bbox -82.705,38.368,-72.565,43.787 north-america.osh.pb -o PA.osm.pbf`

The error message was:
> Node IDs out of order.
> This command expects the input file to be ordered: First nodes in order of ID,
> then ways in order of ID, then relations in order of ID.

What I did to tackle this issue was:
`osmium extract --bbox -82.705,38.368,-72.565,43.787 --with-history -v north-america.osh.pb -o PA.osm.pbf` 


Thank you all and special thanks to Jochen Topf for his great contribution and cooperation.

**Comment by joto** [comment]
@aaabuabat While it is nice that you want to share your experiences with osmium, your contribution has nothing to do with the thread here. This issue is about a totally different thing and your addition is just confusing for everybody. Thats why I'll delete it.

**Comment by aaabuabat** [comment]
So, where is the right place to write this note?

**Comment by joto** [comment]
I have added support for negative IDs to the renumber command, so this should now work in the master branch.

**Comment by aaabuabat** [comment]
Thank you for your great efforts.

**Comment by pnorman** [comment]
Link for cross-reference to the lists: https://lists.openstreetmap.org/pipermail/josm-dev/2017-August/007873.html

**Comment by andrewharvey** [comment]
I can confirm it's working for me now in osmium-tool 1.7.0.
