### ISSUE TITLE
Appveyor build fails

### ISSUE THREAD

**Issue by joto** [osmcode/osmium-tool#33]
Appveyor build fails for some reason that seems not to be related to recent changes in Osmium. There are similar errors in https://github.com/osmcode/osm-gis-export .

@BergWerkGIS Can you take a look?

**Comment by BergWerkGIS** [comment]
@joto looking into it...
Also moving logic from `appveyor.yml` into scripts to make local testing easier: https://github.com/osmcode/osmium-tool/pull/34

**Comment by BergWerkGIS** [comment]
[`error MSB4126: The specified solution configuration "Dev|x64" is invalid.`](https://ci.appveyor.com/project/Mapbox/osmium-tool/build/1.0.175/job/wswnvf3hiojwflfh#L273) occurs because Cmake does not create the configuration `Dev` anymore.

These are the ones that are created:
![image](https://cloud.githubusercontent.com/assets/4549888/18437394/3669aacc-78ec-11e6-9827-03abf3828a27.png)

Reverting your change from `;` to ` ` in [CmakeLists.txt](https://github.com/osmcode/osmium-tool/commit/5e8c299a18af6028eb98e0dec82acf52870e5cf1#diff-af3b638bc2a3e6c650974192a53c7291R211) made the tests run (and pass) again with `RelWithDebInfo`:
https://ci.appveyor.com/project/Mapbox/osmium-tool/build/1.0.179/job/xydlye18vxio54jp#L959

But didn't solve the missing `Dev` configuration as I had hoped.
