### ISSUE TITLE
When deriving diffs, a new object with v=2 is listed in <modify>

### ISSUE THREAD

**Issue by woodpeck** [osmcode/osmium-tool#37]
The correct diff between the two OSM files

```
   <osm version="0.6">
   </osm>
```

and

```
   <osm version="0.6">
      <node id="1" version="2" timestamp="2016-09-14T19:18:17Z" uid="16" user="User" changeset="15" lat="1.413" lon="1.211" />
   </osm>
```

is

```
   <osmChange version="0.6">
     <create>
       <node id="1" version="2" timestamp="2016-09-14T19:18:17Z" uid="16" user="User" changeset="15" lat="1.413" lon="1.211"/>
     </create>
   </osmChange>
```

but osmium-tool derive-change creates a "modify" block instead of the "create" block.

The problem does not appear when the new object has the version number 1.

**Comment by joto** [comment]
If there is a version 2, there must have been a version 1. So "modify" is arguably right. If the two OSM files came from the OSM database, this constellation could never happen, it only happens when there are extracts or so. This is one of those cases where the file format isn't really thought through. Anyway, any program reading this change file will do the same operation anyway, so it shouldn't make a difference.

This is definitely something where we can not "fix" in Osmium, because the reason this comes out this way is deeply embedded into the way Osmium handles changes. Unlike Osmosis, which has "data streams" and "change streams", Osmium only has "objects", the change format is synthesized when writing out an .osc file simply using "create" when version==1 and "modify" when version > 1.

**Comment by woodpeck** [comment]
The diff between two osm files describes "how to get there from here". If file A doesn't have an object, then you do not get to file B by "modifying" that non-existing object! I dont understand why "If the two OSM files came from the OSM database this constellation could never happen" - surely you can have an object not be there in planet file A and be at version 2 in planet file B?

**Comment by joto** [comment]
Because there must have been a version 1. The only version that is ever created out of thin air is version 1. All other versions are modifications of that first version. Yes, we can argue about the the exact definition of the change file and of what "create" and "modify" etc. mean, but in the end all a change file is, is a bunch of OSM objects. And everything that doesn't have a smaller version number than what's existing in your planet file or database, will be added to that planet file or database (and a "delete" is a kind of add in this case, because it adds a newer version marked as "deleted") replacing any older versions if they existed. There is no difference between how "create" or "modify" are handled really, and "delete" is also only special in so far as it basically sets the "visible" flag to false.

**Comment by joto** [comment]
I have clarified this behaviour in the [documentation](http://osmcode.org/file-formats-manual/#file-types).
