### ISSUE TITLE
Feedback for tags-filter

### ISSUE THREAD

**Issue by freenerd** [osmcode/osmium-tool#45]
@joto I've been playing with `osmium tags-filter`, here is some opinions:

- make `--add-referenced` default. `osmium extract` has a default strategy of `complete_ways` and I guess it avoids user error to include as much as possible, then have the user decide to cut down if not needed.
- allow for exclusion. Right now `tags-filter` is inclusive. I guess a common use-case will be to slim down osm extracts so that they can be easier loaded into tools like JOSM. So the user might want to retain everything except a big class of tags, like `building` or `highway`.
- JSON as config format. the current config file feels a bit obscure and `osmium extract` has json config files, so tags-filter could as well. i understand that the current solution is nice because command line arguments and config file are the same, so i'm not sure how to solve this.

**Comment by joto** [comment]
@freenerd Thanks for the feedback.

> - make `--add-referenced` default. `osmium extract` has a default strategy of `complete_ways` and I guess it avoids user error to include as much as possible, then have the user decide to cut down if not needed.

On the other hand, `--add-referenced` is consistent with the same option on the `getid` command. I created a new issue for that: #48.

> - allow for exclusion. Right now `tags-filter` is inclusive. I guess a common use-case will be to slim down osm extracts so that they can be easier loaded into tools like JOSM. So the user might want to retain everything except a big class of tags, like `building` or `highway`.

I added option `-i` or `--invert-match` for this.

> - JSON as config format. the current config file feels a bit obscure and `osmium extract` has json config files, so tags-filter could as well. i understand that the current solution is nice because command line arguments and config file are the same, so i'm not sure how to solve this.

And it is much less verbose than a JSON file. But I do agree that for some cases a JSON file might be preferable, especially because the escaping rules are well defined there, so if we want to match for characters that are special in the current config file, a JSON file might be better than inventing new rules. We can always add a JSON config file later, I'll leave it for the time being and we'll see how it works.

**Comment by freenerd** [comment]
Thanks @joto. Agree with JSON as an option that can also be implemented later.
