### ISSUE TITLE
Ability to set options.timestamp header in osmium apply-changes

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#69]
Is it possible to set `options.timestamp` header in the output `osmium apply-changes`? 
Setting headers isn't documented much, so couldn't find it in the docs yet.

**Comment by joto** [comment]
You should be able to set any header option with `--output-header=OPTION`, but I guess that isn't going to help you much, because I you don't know what to set it to. Unfortunately there are several timestamp headers used and it isn't really clear how they are to be interpreted, so `apply-changes` doesn't do anything automatic there.

If you want to update OSM files fully automatically, I recommend you have a look at the tools in 
https://github.com/osmcode/pyosmium/tree/master/tools .

**Comment by nextstopsun** [comment]
I've tried with latest master and unfortunately still can't set the header.
```
osmium apply-changes -v --output-header='options.timestamp=2017-08-31T08:58:02Z' my.pbf changes.o5c -o new.pbf -O
```

@joto Could you please add some more info on `--output-header` option to the docs? (An example or a list of common headers). It sends to lib osmium docs, and it's quite hard to find the right place with this info from there.

**Comment by joto** [comment]
`--output-header="foo=bar"` should work. Setting headers yourself is a very specialized thing and you have to know what you are doing. This isn't something that the normal user should ever need. Some amount of experimentation is probably required, because there is no clear definition of what those headers mean to which program, so I really don't know how to document this better.

**Comment by nextstopsun** [comment]
Still can't get it to work:
```
osmium apply-changes -v --output-header="timestamp=2017-08-31T08:58:02Z" my.pbf changes.o5c -o new.pbf -O
[ 0:00] Started osmium apply-changes
[ 0:00]   osmium version 1.7.1
[ 0:00]   libosmium version 2.13.1
[ 0:00] Command line options and default settings:
[ 0:00]   input data file name: /mnt/nas/geodata/osm/extracts/RU-MOW-2017-08-31T07:03:02Z.pbf
[ 0:00]   input change file names: 
[ 0:00]     changes.o5c
[ 0:00]   data file format: 
[ 0:00]   change file format: 
[ 0:00]   output options:
[ 0:00]     file name: new.pbf
[ 0:00]     file format: 
[ 0:00]     generator: osmium/1.7.1
[ 0:00]     overwrite: yes
[ 0:00]     fsync: no
[ 0:00]     output header:
[ 0:00]       timestamp=2017-08-31T08:58:02Z
[ 0:00]   reading and writing history file: no
[ 0:00]   locations on ways: no
[ 0:00] Reading change file contents...
[ 0:00] Opening input file...
[ 0:00] Opening output file...
[ 0:00] Sorting change data...
[ 0:00] Applying changes and writing them to output...
[ 0:04] Peak memory used: 377 MBytes
[ 0:04] Done.
```

Looks like the header is set. But when trying to read info there's no `timestamp` header reported:
```
osmium fileinfo  new.pbf
File:
  Name: new.pbf
  Format: PBF
  Compression: none
  Size: 50168079
Header:
  Bounding boxes:
  With history: no
  Options:
    generator=osmium/1.7.1
    pbf_dense_nodes=true
```

Setting like `--output-header="options.timestamp=2017-08-31T08:58:02Z"` has the same effect.

**Comment by joto** [comment]
Ah, sorry. I remembered it wrong. I though you can set any header you like, but that is not the case. PBF only knows about some specific headers and only those are implemented. See http://wiki.openstreetmap.org/wiki/PBF_Format . You have to use the `osmosis_replication_timestamp` instead of `timestamp`. That is the "official name" of that header option. For backwards compatibility this is also available as `timestamp` when reading a file, but when writing only the official name is allowed.

**Comment by nextstopsun** [comment]
Works with `osmosis_replication_timestamp`. Thanks, @joto!!
