### ISSUE TITLE
Add output in o5c format to osmium derive-changes tool

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#74]
While this format can be read by `osmium apply-changes` a natural evolution would be to allow writing to `o5c` by `derive-changes` tool. In some cases changes are quite big, so this would lower disk consuming.

**Comment by joto** [comment]
The `o5m` and `o5c` formats are currently only supported for reading in the libosmium library. I mostly implemented this, because `osm2pgsql` wanted this for backwards compatibility. But I don't see those formats as particularly important. So unless somebody else supplies the code for this, this will most likely not happen.

Use `osc.gz` or `osc.bz2` if your files are too big.
