### ISSUE TITLE
tags-filter on history file without --omit-referenced option

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/osmium-tool#81]
@joto Can you please explain what will happen with history file when using `osmium tags-filter` on it without setting `--omit-referenced` option?
I'd expect it to work like this: all referenced nodes and ways (including their historical versions) are saved to the output file.

**Comment by joto** [comment]
The command will not work correctly, it will not produce any useful output. That's why the man page says "The command will only work correctly on history files if the -R/--omit-referenced option is used." Do not use it that way.

**Comment by nextstopsun** [comment]
Can you please give more details: what output would be produced instead? I need to filter history file by tags, but don't want to loose referenced nodes and ways.

**Comment by joto** [comment]
No, I can't give you more details, because I don't know them myself. Osmium doesn't promise anything. The output is essentially random. You can not use Osmium for this currently (and before you ask: I don't know of any other program that can do this). If it were easy to handle this case, then Osmium would do it and I would have documented what it would do. But it is not that easy, so, sorry, it can't help you here.
